version: '3.8'

services:
  mongo-db:
    image: mongo:6.0
    container_name: mongo-db
    networks:
      - app-network
    ports:
      - "27017:27017"

  backend-app:
    build:
      context: ./backend
    image: backend-app:latest
    container_name: backend-app
    depends_on:
      - mongo-db
      - redis
    networks:
      - app-network
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  frontend-app:
    build:
      context: ./frontend
    image: frontend-app:latest
    container_name: frontend-app
    depends_on:
      - backend-app
    networks:
      - app-network
    ports:
      - "80:80"

  redis:
    image: redis:7
    container_name: redis
    networks:
      - app-network
    ports:
      - "6379:6379"

  redis-exporter:
    image: oliver006/redis_exporter:latest
    container_name: redis-exporter
    environment:
      - REDIS_ADDR=redis:6379
    ports:
      - "9121:9121"
    networks:
      - app-network

  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy
    depends_on:
      - frontend-app
    networks:
      - app-network
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    networks:
      - app-network

networks:
  app-network:
    external: true
